from __future__ import annotations

from incident_env.models import DifficultyLevel, IncidentScenario, ResponseTeam, SeverityLevel


def scenario(
    incident_id: str,
    title: str,
    difficulty: DifficultyLevel,
    alerts: list[str],
    logs: list[str],
    service_map: list[str],
    timeline: list[str],
    correct_severity: SeverityLevel,
    correct_team: ResponseTeam,
    escalation_required: bool,
    service_keywords: list[str],
    impact_keywords: list[str],
    response_keywords: list[str],
    explanation: str,
    status_forbidden_keywords: list[str] | None = None,
) -> IncidentScenario:
    return IncidentScenario(
        incident_id=incident_id,
        title=title,
        difficulty=difficulty,
        alerts=alerts,
        logs=logs,
        service_map=service_map,
        timeline=timeline,
        correct_severity=correct_severity,
        correct_team=correct_team,
        escalation_required=escalation_required,
        service_keywords=service_keywords,
        impact_keywords=impact_keywords,
        response_keywords=response_keywords,
        status_forbidden_keywords=status_forbidden_keywords or [],
        explanation=explanation,
    )


INCIDENT_SCENARIOS = [
    scenario(
        "easy-db-primary-down",
        "Primary database failure blocks order writes",
        DifficultyLevel.EASY,
        alerts=[
            "orders-api error rate 100% for POST /checkout",
            "db-primary heartbeat lost in us-east-1",
            "replica promotion candidate healthy",
        ],
        logs=[
            "orders-api: psycopg connection refused to db-primary",
            "db-primary: instance unreachable after storage fault",
        ],
        service_map=["orders-api -> checkout-worker -> postgres-primary"],
        timeline=[
            "14:01 deploy status unchanged",
            "14:03 db-primary heartbeat lost",
            "14:04 checkout writes failing globally",
        ],
        correct_severity=SeverityLevel.SEV1,
        correct_team=ResponseTeam.DATABASE,
        escalation_required=True,
        service_keywords=["orders", "database", "checkout"],
        impact_keywords=["checkout unavailable", "order writes failing", "customers cannot place orders"],
        response_keywords=["promote replica", "failover", "restore database"],
        explanation="The primary database is down and customer checkout is unavailable, making this a SEV-1 owned by database.",
    ),
    scenario(
        "easy-edge-cert-expired",
        "Expired TLS certificate at edge gateway",
        DifficultyLevel.EASY,
        alerts=[
            "api-gateway HTTPS success rate 0%",
            "certificate expiry monitor critical on edge-gateway-prod",
        ],
        logs=[
            "edge-gateway: tls handshake failed certificate expired",
            "synthetic probes: all regions returning TLS validation error",
        ],
        service_map=["clients -> edge-gateway -> public-api"],
        timeline=[
            "09:55 cert expiry warning ignored",
            "10:00 production certificate expired",
            "10:02 all API traffic failing at edge",
        ],
        correct_severity=SeverityLevel.SEV1,
        correct_team=ResponseTeam.NETWORK,
        escalation_required=True,
        service_keywords=["edge gateway", "tls", "api"],
        impact_keywords=["api unavailable", "all requests failing", "customers blocked"],
        response_keywords=["renew certificate", "rotate certificate", "restore edge traffic"],
        explanation="Traffic never reaches the application tier because the edge TLS certificate expired.",
    ),
    scenario(
        "easy-worker-deploy-regression",
        "Background worker deploy causes queue backlog",
        DifficultyLevel.EASY,
        alerts=[
            "invoice-worker queue depth 12x baseline",
            "invoice processing latency 18 minutes",
        ],
        logs=[
            "invoice-worker: KeyError after build 2026.04.06.2",
            "deployment system: invoice-worker rollout completed 8 minutes ago",
        ],
        service_map=["checkout -> invoice-queue -> invoice-worker"],
        timeline=[
            "16:12 invoice-worker rollout started",
            "16:18 KeyError spikes begin",
            "16:22 backlog passes alert threshold",
        ],
        correct_severity=SeverityLevel.SEV2,
        correct_team=ResponseTeam.BACKEND,
        escalation_required=False,
        service_keywords=["invoice worker", "queue", "invoice processing"],
        impact_keywords=["delayed invoices", "processing delayed", "customers waiting"],
        response_keywords=["rollback deploy", "restart worker", "drain queue"],
        explanation="This is a clear backend regression with significant but not total customer impact.",
    ),
    scenario(
        "easy-cache-memory-pressure",
        "Cache cluster memory pressure increases latency",
        DifficultyLevel.EASY,
        alerts=[
            "redis cache memory 97%",
            "catalog-api p95 latency 3x baseline",
        ],
        logs=[
            "redis-prod: evicted 28000 keys in 5m",
            "catalog-api: elevated cache miss ratio, origin still healthy",
        ],
        service_map=["catalog-api -> redis-cache -> product-db"],
        timeline=[
            "11:10 cache memory crossed 90%",
            "11:14 evictions accelerate",
            "11:18 latency rises but availability remains above 99%",
        ],
        correct_severity=SeverityLevel.SEV3,
        correct_team=ResponseTeam.INFRA,
        escalation_required=False,
        service_keywords=["cache", "catalog api", "redis"],
        impact_keywords=["slower catalog", "latency elevated", "degraded browsing"],
        response_keywords=["scale cache", "increase memory", "rebalance cache"],
        explanation="The cache tier is saturated, but origin systems remain healthy and the issue is moderate.",
    ),
    scenario(
        "easy-auth-timeouts",
        "Authentication service timeouts block logins",
        DifficultyLevel.EASY,
        alerts=[
            "login success rate dropped to 42%",
            "auth-service timeout rate critical",
        ],
        logs=[
            "auth-service: downstream session store timeout after 8s",
            "web-frontend: login request timeout at /oauth/token",
        ],
        service_map=["web-frontend -> auth-service -> session-store"],
        timeline=[
            "08:41 login success steady",
            "08:44 auth-service timeout alert fires",
            "08:46 customer login failures reported",
        ],
        correct_severity=SeverityLevel.SEV2,
        correct_team=ResponseTeam.BACKEND,
        escalation_required=True,
        service_keywords=["auth service", "login", "oauth"],
        impact_keywords=["login failures", "customers cannot sign in", "authentication degraded"],
        response_keywords=["stabilize auth service", "restart auth pods", "mitigate session store timeout"],
        explanation="Customer login is heavily impacted, and the owner is the application auth team.",
    ),
    scenario(
        "easy-payment-webhook-stall",
        "Payment webhooks stalled after queue consumer crash",
        DifficultyLevel.EASY,
        alerts=[
            "payment-webhook consumer count zero",
            "payment reconciliation lag 27 minutes",
        ],
        logs=[
            "payment-webhook-consumer: process exited with out-of-memory",
            "queue-monitor: messages accumulating, producers healthy",
        ],
        service_map=["payment-gateway -> webhook-queue -> payment-webhook-consumer"],
        timeline=[
            "13:05 consumer oom-killed",
            "13:10 lag begins rising",
            "13:22 finance dashboard missing settlements",
        ],
        correct_severity=SeverityLevel.SEV2,
        correct_team=ResponseTeam.BACKEND,
        escalation_required=False,
        service_keywords=["payment webhook", "reconciliation", "queue consumer"],
        impact_keywords=["delayed payment updates", "settlement lag", "payment processing delayed"],
        response_keywords=["restart consumer", "scale consumer", "drain webhook queue"],
        explanation="This is a clear application-consumer failure with significant operational impact but a contained blast radius.",
    ),
    scenario(
        "easy-dns-record-rollback",
        "Misrouted DNS record sends mobile traffic to retired edge",
        DifficultyLevel.EASY,
        alerts=[
            "mobile-api traffic success rate 8%",
            "dns configuration drift detected for m.api.example.com",
        ],
        logs=[
            "resolver checks: mobile DNS target points to decommissioned load balancer",
            "mobile clients: connection refused from retired edge VIP",
        ],
        service_map=["mobile-clients -> mobile-api DNS -> edge-lb"],
        timeline=[
            "17:01 DNS automation applied change",
            "17:03 success rate collapses for mobile only",
            "17:05 desktop traffic remains healthy",
        ],
        correct_severity=SeverityLevel.SEV2,
        correct_team=ResponseTeam.NETWORK,
        escalation_required=True,
        service_keywords=["mobile api", "dns", "edge"],
        impact_keywords=["mobile outage", "mobile requests failing", "customers blocked on mobile"],
        response_keywords=["rollback dns", "restore dns record", "point traffic to active edge"],
        explanation="A network-owned DNS change is causing a major but channel-specific outage.",
    ),
    scenario(
        "easy-observability-noise",
        "Metrics pipeline lag triggers alerts without customer impact",
        DifficultyLevel.EASY,
        alerts=[
            "metrics-ingest backlog critical",
            "dashboard freshness below SLA",
        ],
        logs=[
            "prometheus-remote-write retries increasing",
            "synthetics show public APIs healthy across all regions",
        ],
        service_map=["services -> metrics-agent -> observability-cluster"],
        timeline=[
            "12:12 remote write latency rises",
            "12:14 dashboards stale",
            "12:18 no customer error increase observed",
        ],
        correct_severity=SeverityLevel.SEV4,
        correct_team=ResponseTeam.INFRA,
        escalation_required=False,
        service_keywords=["observability", "metrics pipeline", "dashboard freshness"],
        impact_keywords=["no customer impact", "internal visibility degraded", "monitoring delayed"],
        response_keywords=["restore metrics pipeline", "clear ingest backlog", "recover observability"],
        explanation="The issue is operationally relevant but has no direct customer impact.",
    ),
    scenario(
        "medium-api-db-network-split",
        "Network split between API and database in one production cell",
        DifficultyLevel.MEDIUM,
        alerts=[
            "orders-api error rate 45% in cell-b only",
            "database connection resets increasing",
            "network packet loss 38% between api-subnet-b and db-subnet-b",
        ],
        logs=[
            "orders-api: connection reset by peer while opening db session",
            "db metrics: cpu normal, no lock contention",
        ],
        service_map=["orders-api cell-b -> network fabric -> postgres cluster"],
        timeline=[
            "15:02 packet loss begins in cell-b",
            "15:04 application retries rise",
            "15:07 customer order failures confined to one cell",
        ],
        correct_severity=SeverityLevel.SEV1,
        correct_team=ResponseTeam.NETWORK,
        escalation_required=True,
        service_keywords=["orders api", "database connectivity", "cell-b"],
        impact_keywords=["order failures", "checkout degraded", "customer transactions failing"],
        response_keywords=["stabilize network path", "reroute traffic", "isolate failing network segment"],
        explanation="The database looks healthy; the decisive signal is network packet loss on the failing path.",
    ),
    scenario(
        "medium-memory-leak-after-deploy",
        "Checkout pods leak memory after partial rollout",
        DifficultyLevel.MEDIUM,
        alerts=[
            "checkout-api p95 latency 5x baseline",
            "kubernetes oom kills rising on checkout-api",
            "deployment 2026.04.06.5 at 40% rollout",
        ],
        logs=[
            "checkout-api: heap grew from 600Mi to 2.4Gi in 6 minutes",
            "node resources healthy outside checkout namespace",
        ],
        service_map=["edge -> checkout-api -> pricing-service -> payment"],
        timeline=[
            "18:20 rollout started",
            "18:25 latency starts climbing",
            "18:28 first OOM kill observed",
        ],
        correct_severity=SeverityLevel.SEV2,
        correct_team=ResponseTeam.BACKEND,
        escalation_required=True,
        service_keywords=["checkout api", "memory leak", "rollout"],
        impact_keywords=["checkout slowed", "purchase flow degraded", "customer latency elevated"],
        response_keywords=["halt rollout", "rollback deploy", "stabilize checkout pods"],
        explanation="The workload-specific OOM pattern points to a backend regression introduced by the rollout.",
    ),
    scenario(
        "medium-object-store-slowdown",
        "Object store slowdown delays image uploads",
        DifficultyLevel.MEDIUM,
        alerts=[
            "media-upload success rate 71%",
            "object-store latency 4x in region eu-west",
            "text-posting path healthy",
        ],
        logs=[
            "upload-service: timeout writing object chunks",
            "object-store metrics: elevated internal queue time",
        ],
        service_map=["mobile-app -> upload-service -> object-store"],
        timeline=[
            "10:08 object-store latency rises in eu-west",
            "10:11 image upload errors appear",
            "10:15 text posting remains healthy",
        ],
        correct_severity=SeverityLevel.SEV2,
        correct_team=ResponseTeam.INFRA,
        escalation_required=True,
        service_keywords=["image uploads", "object store", "upload service"],
        impact_keywords=["upload failures", "media posting degraded", "customer uploads delayed"],
        response_keywords=["mitigate object store", "shift traffic", "stabilize upload path"],
        explanation="The dependency tier is degraded regionally and requires infra coordination with escalation.",
    ),
    scenario(
        "medium-auth-failover-working",
        "Primary auth database alert storm while failover preserves service",
        DifficultyLevel.MEDIUM,
        alerts=[
            "auth-db primary cpu 98%",
            "replica promotion event detected",
            "login success rate remains 99.2%",
        ],
        logs=[
            "auth-service: switched to promoted replica successfully",
            "customer-facing error budget unaffected",
        ],
        service_map=["frontend -> auth-service -> auth-db primary/replica"],
        timeline=[
            "07:42 primary cpu spikes",
            "07:44 automatic failover completes",
            "07:48 alerts continue from stale monitors",
        ],
        correct_severity=SeverityLevel.SEV3,
        correct_team=ResponseTeam.DATABASE,
        escalation_required=False,
        service_keywords=["auth database", "failover", "login service"],
        impact_keywords=["service stable", "minimal customer impact", "degraded redundancy"],
        response_keywords=["confirm failover health", "clear stale alerts", "stabilize database redundancy"],
        explanation="There is real operational risk, but customer impact is low because failover succeeded.",
    ),
    scenario(
        "medium-dns-cache-poison",
        "Bad internal DNS cache causes intermittent payment timeouts",
        DifficultyLevel.MEDIUM,
        alerts=[
            "payment-api timeout rate 18%",
            "internal DNS NXDOMAIN spikes in payments namespace",
            "application error messages alternate between timeout and name resolution failure",
        ],
        logs=[
            "payment-api: dial tcp lookup ledger-service on 10.0.0.10: no such host",
            "ledger-service pods healthy and serving direct health checks",
        ],
        service_map=["payment-api -> cluster DNS -> ledger-service"],
        timeline=[
            "19:02 DNS cache corruption begins",
            "19:05 payment timeouts spike",
            "19:09 direct service probes still healthy",
        ],
        correct_severity=SeverityLevel.SEV2,
        correct_team=ResponseTeam.NETWORK,
        escalation_required=True,
        service_keywords=["payment api", "dns", "ledger service"],
        impact_keywords=["payment timeouts", "checkout degraded", "customer payments impacted"],
        response_keywords=["flush dns cache", "restore service discovery", "stabilize name resolution"],
        explanation="The service itself is healthy; service discovery is not.",
    ),
    scenario(
        "medium-rate-limit-config",
        "Rate limit config blocks high-value customers after launch",
        DifficultyLevel.MEDIUM,
        alerts=[
            "premium-checkout HTTP 429 rate 33%",
            "recent config rollout on rate-limit-service",
            "general checkout success remains above 95%",
        ],
        logs=[
            "rate-limit-service: premium tier map missing enterprise_customer group",
            "payment-api itself healthy",
        ],
        service_map=["premium-clients -> edge -> rate-limit-service -> payment-api"],
        timeline=[
            "20:10 config rollout completed",
            "20:13 premium customers report blocks",
            "20:18 free tier unaffected",
        ],
        correct_severity=SeverityLevel.SEV3,
        correct_team=ResponseTeam.BACKEND,
        escalation_required=False,
        service_keywords=["premium checkout", "rate limit", "enterprise customers"],
        impact_keywords=["premium customers blocked", "selective payment degradation", "partial customer impact"],
        response_keywords=["rollback config", "restore premium policy", "fix rate limit mapping"],
        explanation="This is a backend configuration issue with partial impact and no need for broad escalation yet.",
    ),
    scenario(
        "medium-replica-lag-stale-reads",
        "Replica lag serves stale recommendations",
        DifficultyLevel.MEDIUM,
        alerts=[
            "recommendation freshness SLA violated",
            "read replica lag 14 minutes",
            "write path healthy",
        ],
        logs=[
            "recommendation-api: reads served from replica with lag 850s",
            "replica disk IO saturation detected",
        ],
        service_map=["web -> recommendation-api -> read-replica"],
        timeline=[
            "06:30 replica lag starts climbing",
            "06:42 recommendation freshness alerts fire",
            "06:50 checkout path remains healthy",
        ],
        correct_severity=SeverityLevel.SEV3,
        correct_team=ResponseTeam.DATABASE,
        escalation_required=False,
        service_keywords=["recommendations", "replica lag", "stale reads"],
        impact_keywords=["stale recommendations", "experience degraded", "non-critical customer impact"],
        response_keywords=["reduce replica lag", "rebalance reads", "stabilize replica io"],
        explanation="Customer experience is degraded, but this is not a top-severity outage.",
    ),
    scenario(
        "medium-waf-false-positive",
        "WAF rule blocks checkout from one geography",
        DifficultyLevel.MEDIUM,
        alerts=[
            "checkout success down 62% for traffic from BR",
            "waf challenge rate spike after new bot rule",
            "core payment services healthy",
        ],
        logs=[
            "edge-waf: rule 4412 blocking /checkout due to malformed device fingerprint",
            "origin logs show request volume dropped before app tier",
        ],
        service_map=["clients in BR -> edge-waf -> checkout-api"],
        timeline=[
            "21:01 new bot rule deployed",
            "21:04 BR checkout failures increase",
            "21:08 other regions remain normal",
        ],
        correct_severity=SeverityLevel.SEV3,
        correct_team=ResponseTeam.SECURITY,
        escalation_required=True,
        service_keywords=["checkout", "waf", "brazil traffic"],
        impact_keywords=["regional checkout failures", "customers blocked in one geography", "partial outage"],
        response_keywords=["disable waf rule", "tune security rule", "restore checkout traffic"],
        explanation="The issue is security-owned with clear pre-origin blocking and regional impact.",
    ),
    scenario(
        "hard-db-saturation-vs-network-noise",
        "Checkout latency with competing database and network symptoms",
        DifficultyLevel.HARD,
        alerts=[
            "checkout p95 latency 8x baseline",
            "database write lock wait time critical",
            "minor packet retransmits reported on one switch",
        ],
        logs=[
            "postgres-primary: lock timeout on payments table update",
            "payment-service: waiting on transaction commit",
            "network telemetry: retransmits below customer-impact threshold",
        ],
        service_map=["checkout-api -> payment-service -> postgres-primary"],
        timeline=[
            "14:10 payment write lock contention increases",
            "14:12 checkout latency rises globally",
            "14:14 network warning appears but remains localized",
        ],
        correct_severity=SeverityLevel.SEV1,
        correct_team=ResponseTeam.DATABASE,
        escalation_required=True,
        service_keywords=["checkout", "database saturation", "payment writes"],
        impact_keywords=["checkout severe latency", "payment delays", "global purchase impact"],
        response_keywords=["reduce lock contention", "stabilize database", "shift write load"],
        explanation="The customer-impacting bottleneck is database write contention; the network signal is distracting noise.",
        status_forbidden_keywords=["network outage"],
    ),
    scenario(
        "hard-deploy-vs-cache-conflict",
        "Error spike after deploy with cache misses masking root cause",
        DifficultyLevel.HARD,
        alerts=[
            "search-api HTTP 500 rate 24%",
            "cache miss ratio 5x baseline",
            "search-api deployment completed 11 minutes ago",
        ],
        logs=[
            "search-api: null pointer in query normalizer introduced in build 2026.04.06.9",
            "cache cluster healthy but misses rise because requests fail before warmup",
        ],
        service_map=["edge -> search-api -> query-cache -> search-index"],
        timeline=[
            "22:10 deploy started",
            "22:17 500 errors begin",
            "22:19 cache misses rise as failed requests bypass warm responses",
        ],
        correct_severity=SeverityLevel.SEV2,
        correct_team=ResponseTeam.BACKEND,
        escalation_required=True,
        service_keywords=["search api", "deployment regression", "search errors"],
        impact_keywords=["search failing", "customer searches degraded", "query errors"],
        response_keywords=["rollback deploy", "stabilize search api", "mitigate application exception"],
        explanation="The cache misses are secondary; the application deploy introduced the customer-impacting fault.",
        status_forbidden_keywords=["cache cluster outage"],
    ),
    scenario(
        "hard-edge-cert-vs-grpc-reset",
        "Mixed edge certificate warnings and internal gRPC resets",
        DifficultyLevel.HARD,
        alerts=[
            "public-api error rate 31%",
            "internal service mesh gRPC resets rising",
            "one edge certificate chain warning present but not expired",
        ],
        logs=[
            "service-mesh: mTLS handshake failures between gateway and profile-service",
            "edge cert lint warning: intermediate chain renews in 12 days",
            "clients receive 503 from gateway after upstream reset",
        ],
        service_map=["clients -> gateway -> service-mesh -> profile-service"],
        timeline=[
            "05:02 upstream resets begin",
            "05:06 gateway 503 responses rise",
            "05:08 cert warning appears in unrelated monitor",
        ],
        correct_severity=SeverityLevel.SEV2,
        correct_team=ResponseTeam.NETWORK,
        escalation_required=True,
        service_keywords=["gateway", "service mesh", "grpc resets"],
        impact_keywords=["api errors", "customer requests failing", "service degraded"],
        response_keywords=["restore mesh connectivity", "stabilize mTLS", "reroute upstream traffic"],
        explanation="The real issue is internal network and mTLS connectivity, not public certificate expiry.",
        status_forbidden_keywords=["certificate expired"],
    ),
    scenario(
        "hard-iam-rotation-auth-failures",
        "IAM rotation coincides with authentication failures and noisy DB metrics",
        DifficultyLevel.HARD,
        alerts=[
            "login success rate 58%",
            "database cpu 72% but stable",
            "token signing key rotation completed 6 minutes ago",
        ],
        logs=[
            "auth-service: signature validation failed for newly issued tokens",
            "db query latency unchanged",
            "security control plane shows partially propagated signing keys",
        ],
        service_map=["frontend -> auth-service -> key-management-service"],
        timeline=[
            "02:10 key rotation triggered",
            "02:13 login failures begin",
            "02:16 db cpu remains elevated but unchanged from baseline",
        ],
        correct_severity=SeverityLevel.SEV2,
        correct_team=ResponseTeam.SECURITY,
        escalation_required=True,
        service_keywords=["authentication", "token validation", "signing keys"],
        impact_keywords=["login failures", "customers cannot sign in reliably", "authentication degraded"],
        response_keywords=["stabilize key propagation", "rollback key rotation", "restore token validation"],
        explanation="The security key propagation issue is the direct cause of login failures.",
        status_forbidden_keywords=["database outage"],
    ),
    scenario(
        "hard-region-outage-autoscaling-noise",
        "Regional outage with autoscaling lag and packet loss symptoms",
        DifficultyLevel.HARD,
        alerts=[
            "region us-west request failure rate 48%",
            "compute autoscaling lag 9 minutes",
            "packet loss spikes on one availability zone uplink",
        ],
        logs=[
            "regional load balancer unable to place traffic due to insufficient healthy instances",
            "packet loss isolated to drained zone after failover",
        ],
        service_map=["clients us-west -> regional-lb -> app fleet"],
        timeline=[
            "03:40 instance churn begins in us-west",
            "03:44 healthy capacity drops below threshold",
            "03:46 packet loss appears as overloaded zone drains",
        ],
        correct_severity=SeverityLevel.SEV1,
        correct_team=ResponseTeam.INFRA,
        escalation_required=True,
        service_keywords=["regional outage", "healthy capacity", "us-west"],
        impact_keywords=["regional customer failures", "major outage", "requests failing"],
        response_keywords=["restore capacity", "shift regional traffic", "stabilize app fleet"],
        explanation="Capacity collapse is the primary issue; packet loss is a downstream symptom.",
        status_forbidden_keywords=["network root cause confirmed"],
    ),
    scenario(
        "hard-third-party-tax-service",
        "Checkout slowdown with dependency outage outside the platform",
        DifficultyLevel.HARD,
        alerts=[
            "checkout completion down 22%",
            "tax-calculation request latency 12x baseline",
            "internal payment and inventory services healthy",
        ],
        logs=[
            "checkout-api: timeout waiting for third-party tax quote",
            "circuit breaker entering half-open state repeatedly",
        ],
        service_map=["checkout-api -> tax-provider -> payment"],
        timeline=[
            "12:03 tax provider latency rises",
            "12:07 checkout latency climbs",
            "12:09 fallback path disabled for taxable regions",
        ],
        correct_severity=SeverityLevel.SEV2,
        correct_team=ResponseTeam.BACKEND,
        escalation_required=True,
        service_keywords=["checkout", "tax provider", "tax quote"],
        impact_keywords=["checkout slowed", "purchase abandonment risk", "customer latency elevated"],
        response_keywords=["degrade dependency", "enable fallback", "mitigate tax provider latency"],
        explanation="The application team owns the mitigation even though the dependency is external.",
    ),
    scenario(
        "hard-observability-false-sev1",
        "Observability outage creates broad false positives with low customer impact",
        DifficultyLevel.HARD,
        alerts=[
            "multiple services report 0% availability from internal telemetry",
            "synthetic probes and revenue counters remain healthy",
            "trace collector storage full",
        ],
        logs=[
            "otel-collector: dropping spans due to full backend",
            "customer-facing APIs returning normal success rates in independent probes",
        ],
        service_map=["services -> otel-collector -> trace-storage"],
        timeline=[
            "04:11 trace storage fills",
            "04:14 internal dashboards collapse across many services",
            "04:17 external probes still green",
        ],
        correct_severity=SeverityLevel.SEV4,
        correct_team=ResponseTeam.INFRA,
        escalation_required=False,
        service_keywords=["observability", "trace collector", "monitoring outage"],
        impact_keywords=["no customer impact", "internal visibility degraded", "false positives"],
        response_keywords=["recover trace storage", "restore telemetry", "stabilize observability pipeline"],
        explanation="This looks dramatic in telemetry but is not a customer-facing outage.",
        status_forbidden_keywords=["global production outage"],
    ),
    scenario(
        "hard-control-plane-failure",
        "Cluster control plane failure blocks remediation during live outage",
        DifficultyLevel.HARD,
        alerts=[
            "public-api failure rate 68%",
            "kubernetes api unavailable in primary region",
            "rollback automation cannot connect to control plane",
        ],
        logs=[
            "incident bot: rollback aborted because kube-apiserver timed out",
            "ingress pods healthy in secondary region but traffic not shifted yet",
        ],
        service_map=["clients -> primary region ingress -> app pods", "secondary region ready but idle"],
        timeline=[
            "23:01 control plane starts timing out",
            "23:04 api failures spike as unhealthy pods cannot be replaced",
            "23:06 automation unable to perform rollback",
        ],
        correct_severity=SeverityLevel.SEV1,
        correct_team=ResponseTeam.SRE,
        escalation_required=True,
        service_keywords=["control plane", "public api", "regional failover"],
        impact_keywords=["major outage", "api failures", "customers blocked"],
        response_keywords=["trigger regional failover", "restore control plane", "coordinate manual mitigation"],
        explanation="This is an SRE-led incident because platform control-plane failure blocks normal app recovery.",
    ),
    scenario(
        "hard-latency-mixed-signals",
        "Latency spike with conflicting infra and application signals",
        DifficultyLevel.HARD,
        alerts=[
            "api latency p95 critical",
            "database cpu high",
            "cache miss rate increased after rollout",
        ],
        logs=[
            "db queries slower but within limits",
            "cache evictions increased after deploy",
            "error rate only slightly elevated",
            "release tracker: checkout-api build 2026.04.07.3 reached 60% rollout",
        ],
        service_map=["api -> cache -> database"],
        timeline=[
            "10:02 deploy pushed",
            "10:05 latency spike begins",
            "10:07 db cpu increases",
            "10:09 cache miss rate jumps",
        ],
        correct_severity=SeverityLevel.SEV2,
        correct_team=ResponseTeam.BACKEND,
        escalation_required=True,
        service_keywords=["api", "latency", "rollout"],
        impact_keywords=["degraded", "slow", "customer latency elevated"],
        response_keywords=["rollback", "fix deploy", "stabilize api"],
        explanation="The infrastructure signals are noisy, but the decisive clue is the rollout-correlated latency change.",
        status_forbidden_keywords=["database outage", "cache cluster outage"],
    ),
    scenario(
        "hard-false-positive-infra",
        "High infra alerts but stable customer traffic",
        DifficultyLevel.HARD,
        alerts=[
            "node cpu critical",
            "memory pressure high",
            "disk io spike",
        ],
        logs=[
            "background batch jobs running on shared nodes",
            "customer endpoints stable across synthetic probes",
            "no increase in error rate or latency",
        ],
        service_map=["batch-jobs -> infra-nodes"],
        timeline=[
            "02:00 batch jobs start",
            "02:05 infra alerts trigger",
            "02:10 traffic remains stable",
        ],
        correct_severity=SeverityLevel.SEV4,
        correct_team=ResponseTeam.INFRA,
        escalation_required=False,
        service_keywords=["infra", "batch jobs", "shared nodes"],
        impact_keywords=["no customer impact", "service stable", "internal capacity pressure"],
        response_keywords=["monitor", "optimize", "rebalance nodes"],
        explanation="The alerts are loud, but customer traffic is healthy and the issue is internal infrastructure load.",
        status_forbidden_keywords=["outage", "downtime", "customers blocked"],
    ),
    scenario(
        "hard-auth-failure-conflict",
        "Authentication failures with mixed security and service signals",
        DifficultyLevel.HARD,
        alerts=[
            "login failure rate spike",
            "token validation errors increasing",
            "unusual auth traffic pattern detected",
        ],
        logs=[
            "recent key rotation completed 7 minutes ago",
            "backend auth service latency normal",
            "signature mismatch detected on newly issued tokens",
        ],
        service_map=["api -> auth-service -> key-store"],
        timeline=[
            "09:00 key rotation deployed",
            "09:05 login failures increase",
            "09:07 unusual token errors spread across regions",
        ],
        correct_severity=SeverityLevel.SEV2,
        correct_team=ResponseTeam.SECURITY,
        escalation_required=True,
        service_keywords=["auth", "token", "login failures"],
        impact_keywords=["login failures", "customers cannot sign in reliably", "authentication degraded"],
        response_keywords=["rollback key", "restore token validation", "stabilize auth"],
        explanation="The auth service itself is healthy; the security key change is breaking validation.",
        status_forbidden_keywords=["backend failure", "auth service outage"],
    ),
    scenario(
        "hard-regional-routing-imbalance",
        "Regional failure masked as global degradation",
        DifficultyLevel.HARD,
        alerts=[
            "api latency elevated globally",
            "packet loss detected on one regional edge path",
            "error rate increased unevenly across zones",
        ],
        logs=[
            "region-us-east failing to accept shifted traffic",
            "other regions healthy but overloaded during imbalance",
            "routing policy did not fail traffic away cleanly",
        ],
        service_map=["global-lb -> regional clusters"],
        timeline=[
            "14:01 us-east failure begins",
            "14:03 global latency rises",
            "14:05 routing imbalance detected",
        ],
        correct_severity=SeverityLevel.SEV1,
        correct_team=ResponseTeam.NETWORK,
        escalation_required=True,
        service_keywords=["region", "routing", "network"],
        impact_keywords=["outage", "request failures", "customer degradation"],
        response_keywords=["reroute", "failover", "stabilize network path"],
        explanation="It looks global at first, but the real issue is regional routing and failover behavior on the network path.",
        status_forbidden_keywords=["global infra down", "database outage"],
    ),
]
